config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :printers, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:index, :new, :create]
    resources :reviews, only: [:show, :new, :create]
  end
  resources :bookings, only: [:show, :edit, :update, :destroy]

  get "/bookings", to: "bookings#my_bookings", as: :my_bookings
  get "/my_printers", to: "printers#my_printers", as: :my_printers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :printer
  has_many :notifications
  validates :meeting_time, presence: true
  validates :status, presence: true
  validates :status, inclusion: {in: ["Pending", "Accepted", "Rejected", "Completed"]}
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :booking
  
end

app/models/printer.rb
class Printer < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  validates :price, presence: true
  validates :model, :photo, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :printer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :printers
  has_many :reviews
  has_many :notifications
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :address, presence: true
  validates :is_owner, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :is_owner, :rating])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :is_owner, :rating])
  end

  def user_not_authorized
     flash[:alert] = "You are not authorized to perform this action."
     redirect_to(root_path)
  end

  def after_sign_in_path_for(resource)
    resource.is_owner ? my_bookings_path(resource) : printers_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

 before_action :authenticate_user!, except: [:index, :show]

  def index
    @printer = Printer.find(params[:printer_id])
    @bookings = policy_scope(@printer.bookings)
  end

  def new
    @printer = Printer.find(params[:printer_id])
    @booking = Booking.new
    request.remote_ip
    raise
    authorize @printer
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.printer = Printer.find(params[:printer_id])
    @booking.user = current_user
    @booking.status = "Pending"
    authorize @booking
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @printer = @booking.printer
    @user = @printer.user
    authorize @booking
    authorize @printer
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = params[:booking][:status]
    @notification = Notification.new
    @notification.booking = @booking 
    @notification.user = @booking.user 
    @notification.text = "Your booking for #{@booking.printer.model} is #{@booking.status}"
    @notification.save
    authorize @booking
    if @booking.save
      redirect_to my_bookings_path(@booking)
    else
      render :edit
    end
  end

  def destroy
    @printer = Booking.find(params[:id]).printer
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to printer_bookings_path(@printer)
  end

  def my_bookings
    if current_user.is_owner
      @bookings = Booking.joins(:printer).where(printers: {user: current_user})
    else
      @bookings = current_user.bookings
    end
    @review = Review.new
    authorize Booking
  end

  private
  def booking_params
    params.require(:booking).permit(:meeting_time, :status)
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController

 before_action :authenticate_user!, except: [:index, :show]

  def index
    @printers = policy_scope(Printer)
    @printers = @printers.geocoded
    @markers = @printers.map do |printer|
      {
        lat: printer.latitude,
        lng: printer.longitude,
        infoWindow: render_to_string(partial: "shared/info_window", locals: { printer: printer })
      }
    end
    @booking = Booking.new
  end

  def show
    @printer = Printer.find(params[:id])
    @booking = Booking.new
    authorize @printer
    authorize @booking
  end

  def new
    @printer = Printer.new
    authorize @printer
  end

  def create
    @printer = Printer.new(printer_params)
    @printer.user = current_user
    authorize @printer
    if @printer.save
      redirect_to printer_path(@printer)
    else
      render :new
    end
  end

  def destroy
    set_printer
    @printer.destroy
    redirect_to printers_path
  end

  def my_printers
    @printers = current_user.printers
    authorize @printers

  end

  private

  def printer_params
    params.require(:printer).permit(:model, :price, :photo)
  end

  def set_printer
    @printer = Printer.find(params[:id])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  # skip_after_action :verify_authorized

  def new
    @printer = Printer.find(params[:printer_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(booking_params)
    @review.printer = Printer.find(params[:printer_id])
    @review.user = current_user
    @review.name = current_user.name

    authorize @review
    if @review.save
      redirect_to printer_path(@review.printer)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:review).permit(:name, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_review_card.html.erb
<div class="container">
  <div class="row justify-content-center py-2">
    <div class="col-md-12">
      <%= simple_form_for [ printer, review ] do |f| %>
        <%= f.input :text, label: false %>
        <%= f.button :submit, "Add Review", class: "btn-flat" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<h2>Edit booking for <%= @booking.printer.model %> </h2>
<%= simple_form_for @booking do |f| %>
  <%= f.input :status, as: :radio_buttons, collection: ["Accepted", "Rejected"]  %>
  <%= f.button :submit, "Update" %>
<% end %>

app/views/bookings/index.html.erb
<div class="form-content m-3 p-3">
  <h2 class="ml-3 mt-2" style="font-weight: bold;"> All your bookings </h2>
  <div class="container-fluid">
    <div class="row">
      <div style = "box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);" class="form-content col-sm m-3 p-2">
        <h3 style="font-weight: bold;" class="m-2 text-warning">Pending Bookings</h3>
        <hr />
        <ul id='sort-lists1' style="padding: 0;">
          <% @bookings.each do |booking| %>
            <% if booking.status == "Pending"%>
              <li style="list-style: none;">
                <div class="card-product no-shadow">
                  <img src="<%= cl_image_path booking.printer.photo.key, height: 300, width: 400, crop: :fill %>"/>
                  <div class="card-product-infos">
                    <h2>Booking for <%= booking.printer.model %> </h2>
                    <% if current_user.is_owner %>
                      <%= simple_form_for(booking) do |f|%>
                        <%= f.input :status, collection: ["Accepted", "Rejected"], default: true, label: "Change Status" %>
                        <%= f.button :submit, "Update", class:"btn btn-flat m-3" %>
                      <% end %>
                    <% else %>
                      <p>Meeting Time: <%= booking.meeting_time %></p>
                      <p>Address: <%= booking.printer.user.address %></p>
                      <p>Status: <%= booking.status %></p>
                    <% end %>
                  </div>
                </div>
              </li>
            <%end%>
          <%end%>
        </ul>
      </div>
      <div style = "box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);" class="form-content col-sm m-3 p-2">
        <h3 style="font-weight: bold;" class="m-2 text-success">Accepted Bookings</h3>
        <hr />
        <ul id='sort-lists2' style="padding: 0;">
          <% @bookings.each do |booking| %>
            <% if booking.status == "Accepted"%>
              <li style="list-style: none;">
                <div class="card-product no-shadow">
                  <img src="<%= cl_image_path booking.printer.photo.key, height: 300, width: 400, crop: :fill %>"/>
                  <div class="card-product-infos">
                    <h2>Booking for <%= booking.printer.model %> </h2>
                    <% if current_user.is_owner %>
                      <%= simple_form_for(booking) do |f|%>
                        <%= f.input :status, collection: ["Completed", "Rejected"], default: true, label: "Change Status" %>
                        <%= f.button :submit, "Update", class:"btn btn-flat m-3" %>
                      <% end %>
                    <% else %>
                      <p>Meeting Time: <%= booking.meeting_time %></p>
                      <p>Address: <%= booking.printer.user.address %></p>
                      <p>Status: <%= booking.status %></p>
                    <% end %>
                  </div>
                </div>
              </li>
            <%end%>
          <%end%>
        </ul>
      </div>
      <div style = "box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2);" class="form-content col-sm m-3 p-4">
        <h3 style="font-weight: bold;" class="m-2 text-primary">Completed Bookings</h3>
        <hr />
        <ul id='sort-lists2' style="padding: 0;">
          <% @bookings.each do |booking| %>
            <% if booking.status == "Completed"%>
              <li style="list-style: none;">
                <div class="card-product no-shadow">
                  <img src="<%= cl_image_path booking.printer.photo.key, height: 300, width: 400, crop: :fill %>"/>
                  <div class="card-product-infos">
                    <h2>Booking for <%= booking.printer.model %> </h2>
                    <p>Meeting Time: <%= booking.meeting_time %></p>
                    <p>Address: <%= booking.printer.user.address %></p>
                    <p>Status: <%= booking.status %></p>
                  </div>
                </div>
              </li>
            <%end%>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center py-5">
    <div class="form-content col-sm-12 col-md-8 col-lg-10 my-5 p-5">
      <h2 class="my-3">Book <%= @printer.model %> </h2>
        <%= simple_form_for [@printer, @booking] do |f| %>
        <%= f.text_field :meeting_time, placeholder: 'Choose a date that works for you', data: { behavior: "flatpickr" }, class: "mb-4"%>
        <%= f.button :submit, "Book Printer", class: "btn-flat my-3" %>
        <% if current_user && current_user.is_owner %>
          <%=link_to "Cancel", printers_path(@printer), class: "btn btn-flat"%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row justify-content-center py-5">
    <div class="form-content col-sm-12 col-md-8 col-lg-10 my-5 p-5">
      <h1>Booking Details</h1>

      <h3>Booking with <%= @user.name %>'s <%= @printer.model %> at <%= @booking.meeting_time %></h3>

      <br>

      <%= link_to edit_booking_path(@booking) do%>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to booking_path(@booking), :method => :delete do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
      <p>Status: <%= @booking.status %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrintsCharming</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <p class="alert alert-primary" style="<%= 'display:none' if notice.nil? %>" ><%= notice %></p>
    <p class="alert alert-danger" style="<%= 'display:none' if alert.nil? %>"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dgudbai8t/image/upload/v1597773767/test_bdpvp5.jpg);">
  <div class="wrapper">
        <h1>Prints Charming brings <strong>print outs</strong> to <strong>disorganized people</strong>!</h1>
          <p><span id="banner-typed-text"></span></p>
          <%= link_to 'Find a Printer', printers_path, class:'btn btn-flat' %>
  </div>
</div>

app/views/printers/_show_card.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="form-content col-sm-12 col-md-12 col-lg-12 my-1 p-2">
      <h1><strong>Model: </strong><%= printer.model %></h1>
      <h1><strong>Price: </strong>$<%= printer.price %></h1>
      <div class="card-category mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path printer.photo.key, height: 300, width: 400, crop: :fill %>') ">
      </div>
      
      <% if current_user && printer.user == current_user %>
      <h5 style="text-align:right;"><%= pluralize printer.bookings.where("status = 'Pending'").size, "Pending Bookings" %></h5>
        <%= link_to "See all bookings for this printer", printer_bookings_path(printer), class: "btn btn-flat mt-3 p-3 w-100" %>
        <%=link_to "Cancel", printers_path(printer), class: "btn btn-dark rounded mt-3 w-100"%>
        <div class="container-fluid mt-3 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <% elsif user_signed_in? && !current_user.is_owner?%>
        <h5>Owned by: <%= printer.user.name %></h5>
        <h5>Address: <%=  printer.address %></h5>
        <hr />
        <div class="container container pl-0 mb-1">
          <div class="row justify-content-left pl-1">
            <div class="form-content col-sm-12 col-md-8 col-lg-12 my-2 p-2 ml-1">
              <h2 class="mb-4">Book this printer </h2>
                <%= simple_form_for [printer, booking] do |f| %>
                <%= f.text_field :meeting_time, placeholder: 'Choose a date that works for you', data: { behavior: "flatpickr" }, class: "mb-4"%>
                <%= f.button :submit, "Book Printer", class: "btn-flat mt-4 py-3 w-100" %>
              <% end %>
              <%=link_to "Cancel", printers_path(printer), class: "btn btn-dark rounded mt-3 w-100 "%>
            </div>
          </div>
        </div>

        <div class="container-fluid mt-3 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <% elsif current_user && current_user.is_owner? %>
        <h5>Owned by: <%= printer.user.name %></h5>
        <h5>Address: <%=  printer.address %></h5>
        <hr />
        <div class="container-fluid mt-3 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <%else %>
        <h5>Owned by: <%= printer.user.name %></h5>
        <h5>Address: <%=  printer.address %></h5>
        <hr />
        <%= link_to "Sign in to book this printer", new_printer_booking_path(printer), class: "btn btn-flat mb-3 w-100" %>
        <div class="container-fluid mt-3 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/printers/index.html.erb
<div class="printers_header m-3">
</div>

<div class = "container">
  <div class="row align-items-start">
    <div class="col">
      <div id="map"
           style="width: 100%; height: 600px; border-radius:5px;"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
<div class="col p-0">
  <div class="container mt-3 p-0">
    <div class="cards">
      <% @printers.each do |printer| %>
        <div class="card-trip">
          <img src="<%= cl_image_path printer.photo.key, height: 300, width: 400, crop: :fill %>"/>
          <div class="card-trip-infos">
            <div class="col-md-12 text-center">
              <h2><%= printer.model %></h2>
              <% if current_user && current_user == printer.user %>
                <p><%= link_to "See bookings for this printer", printer_bookings_path(printer), class: "btn btn-flat mt-3" %></p>
              <%else %>
                <button type="button" class="btn btn-flat mt-3" data-toggle="modal" data-target="#printer-<%=printer.id%>">
                 <%= current_user && current_user.is_owner ? "Read reviews for this printer" : "Read more about this printer"%>  
                </button>


                <div class="modal fade" id="printer-<%=printer.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Detailed Printer Info</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <%= render partial: "show_card", locals: {printer: printer, booking: @booking}%>
                      </div>
                    </div>
                  </div>
                </div>

              <%end%>
            </div>
          </div>
        </div>
      <% end %>



    </div>
  </div>
</div>

app/views/printers/my_printers.html.erb
<div style="margin-top: 5rem;">
  <div class="container">
    <div class="cards">
      <% @printers.each do |printer| %>
        <div class="card-trip">
          <img src="<%= cl_image_path printer.photo.key, height: 300, width: 400, crop: :fill %>"/>
          <div class="card-trip-infos">
            <div class="col-md-12 text-center">
              <h2><%= printer.model %></h2>
              <p><%= link_to "See bookings for this printer", printer_bookings_path(printer), class: "btn btn-flat mt-3" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/printers/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="form-content col-sm-12 col-md-6 my-5 p-4">
      <div class="card-category mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @printer.photo.key, height: 300, width: 400, crop: :fill %>') ">
      </div>
      <h2><strong>Model: </strong><%= @printer.model %></h2>
      <h2><strong>Price: </strong>$<%= @printer.price %></h2>
      <% if current_user && @printer.user == current_user %>
      <h5 style="text-align:right;"><%= pluralize @printer.bookings.where("status = 'Pending'").size, "Pending Bookings" %></h5>
        <%= link_to "See all bookings for this printer", printer_bookings_path(@printer), class: "btn btn-flat mt-3 p-3 w-100" %>
        <%=link_to "Cancel", printers_path(@printer), class: "btn btn-dark rounded mt-3 w-100"%>
        <div class="container-fluid mt-5 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if @printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% @printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <% elsif user_signed_in? && !current_user.is_owner?%>
        <h5>Owned by: <%= @printer.user.name %></h5>
        <h5>Address: <%=  @printer.address %></h5>
        <hr />

        <div class="container-fluid mt-5 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if @printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% @printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
        <div class="container container pl-0">
          <div class="row justify-content-left pl-1">
            <div class="form-content col-sm-12 col-md-8 col-lg-12 my-2 p-2">
              <h2 class="mb-4">Book this printer </h2>
                <%= simple_form_for [@printer, @booking] do |f| %>
                <%= f.text_field :meeting_time, placeholder: 'Choose a date that works for you', data: { behavior: "flatpickr" }, class: "mb-4"%>
                <%= f.button :submit, "Book Printer", class: "btn-flat mt-4 py-3 w-100" %>
              <% end %>
              <%=link_to "Cancel", printers_path(@printer), class: "btn btn-dark rounded mt-3 w-100 "%>
            </div>
          </div>
        </div>
      <% elsif current_user && current_user.is_owner? %>
        <h5>Owned by: <%= @printer.user.name %></h5>
        <h5>Address: <%=  @printer.address %></h5>
        <hr />
        <div class="container-fluid mt-5 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if @printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% @printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <%else %>
        <h5>Owned by: <%= @printer.user.name %></h5>
        <h5>Address: <%=  @printer.address %></h5>
        <hr />
        <div class="container-fluid mt-5 p-3" style="box-shadow: 0px 0px 5px rgba(0,0,0,0.2); border-radius: 10px;">
          <div>
            <h3 style="text-align: center; font-weight: bold;">Reviews</h3>
            <hr /> 
            <% if @printer.reviews.empty? %>
              <p>No reviews yet</p>
            <% else %>
              <% @printer.reviews.each do |review| %>
              <div>
                <p><strong><%= review.name %></strong>: <%= review.text %></p>
              </div>
              <% end %>
              </ul>
            <% end %>
          </div>
        </div>
        <%= link_to "Sign in to book this printer", new_printer_booking_path(@printer), class: "btn btn-flat mt-3 w-100" %>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%=link_to root_path, class:"navbar-brand" do %>
    <i class="fas fa-print"></i>
    <span class="logo">Prints Charming </span>
    <% if user_signed_in? %>
      <div class="dropdown mt-1" style="font-size: 35px;">
        <%= link_to "#", id:"noti-drop" do %> 
          <i class="far fa-bell"></i>
        <%end%>
        <div id="notiDropDown" class="dropdown-menu">
          <% current_user.notifications.reverse.each do |notification| %>
            <%=link_to notification.text, "#", class:"dropdown-item my-2"%>
          <%end%>
        </div>
      </div>
    <%end%>

  <%end%>
  <div class="nav-collapse">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <div class="dropdown">
            <%= link_to current_user.name, "#", class:"btn btn-secondary dropdown-toggle m-2", id:"drop-button"%>
            <div id="myDropdown" class="dropdown-menu">
              <% if current_user.is_owner %>
                <%= link_to 'Add Your Printer', new_printer_path, class:"dropdown-item my-2"%>
                <%= link_to "My Printers", my_printers_path, class:"dropdown-item my-2" %>
              <% end %>
              <%= link_to "My Bookings", my_bookings_path, class:"dropdown-item my-2" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"dropdown-item my-2 " %>
            </div>
          </div>
        </li>
      </ul>
    <% else %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%=link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%=link_to "Login", new_user_session_path, class:"nav-link"%>
      </li>
    </ul>
    <% end %>
  </div>
</div>